---
- name: Installing apache2
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - apache2
    - php7.0
    - libapache2-mod-php7.0
    - php7.0-pgsql

- name: Downloading and unzipping Drupal
  unarchive:
    src: https://www.drupal.org/download-latest/tar.gz
    dest: /var/www
    remote_src: yes
