---
- name: Installing apache2
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - apache2
    - php7.0
    - libapache2-mod-php7.0
    - php7.0-pgsql
    - python-git

- name: Cloning Drupal
  git:
    repo: https://github.com/drupal/drupal.git
    dest: /var/www/drupal/
