---
- name: Installing apache2
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - apache2
    - php7.0
    - libapache2-mod-php7.0
    - php7.0-pgsql

- name: Unzipping Drupal
  copy:
    src: drupal-8.6.7.zip
    dest: /var/www/
