---
- name: Installing apache2
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - apache2
    - php7.0
    - libapache2-mod-php7.0
    - php7.0-pgsql
    - python-git

- name: Cloning Drupal
  git:
    repo: https://github.com/drupal/drupal.git
    dest: /var/www/drupal/

- name: Setting up a new virtual host
  copy:
    src: etc/apache2/sites-available/drupal.conf
    dest: /etc/apache2/sites-available/drupal.conf 
    owner: root
    group: root
    mode: 0644

- name: Activating virtual host
  file:
    src: /etc/apache2/sites-available/drupal.conf
    dest: /etc/apache2/sites-enabled/drupal.conf
    owner: root
    group: root
    state: link

- name: Deleting default virtual host
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify:
    - restart apache2
