---
- name: Install Drupal with Apache, mod-php,PostgreSQL and bind9 as DNS
  hosts: all
  become: yes
  roles:
    - common

- hosts: nodo1
  gather_facts: no
  become: yes
  roles:
    - database
    - dns
