---
- name: Installing PostgreSQL
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Adding Drupal database
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:
    name: "{{ db_name }}"
    encoding: UTF-8

- name: Adding Drupal user to database and granting privileges
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_passwd }}"
    priv: "ALL"
    expires: infinity

- name: Copying database dump file
  copy:
    src: backups/drupal.sql
    dest: /var/lib/postgresql/drupal.sql

- name: Restoring database
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:
    name: "{{ db_name }}"
    state: restore
    target: /var/lib/postgresql/drupal.sql
  notify:
    - restart postgresql
