---
- name: Installing PostgreSQL
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Adding Drupal database
  postgresql_db:
    name: drupal
    encoding: UTF-8

- name: Adding Drupal user to database and granting privileges
  postgresql_user:
    db: drupal
    name: admin
    password: admin
    priv: "ALL"
    expires: infinity
  notify:
    - restart postgresql
