---
- name: Downloading Drupal
  unarchive:
    src: https://www.drupal.org/download-latest/tar.gz
    dest: /var/www/
    remote_src: yes

- name: Renaming Drupal directory
  shell: mv /var/www/drupal* /var/www/drupal
  notify:
    - restart apache2
