---
- name: Downloading Drupal
  unarchive:
    src: https://www.drupal.org/download-latest/tar.gz
    dest: /var/www/
    remote_src: yes

    #- name: Renaming Drupal directory
    #  shell: mv /var/www/drupal* /var/www/drupal

- name: Creating sites/default/files
  file:
    path: /var/www/drupal/sites/default/files
    state: directory
    owner: root
    group: root
    mode: 0666

- name: Copying settings.php file
  copy:
    src: var/www/drupal/sites/default/settings.php
    dest: /var/www/drupal/sites/default/settings.php 
    owner: root
    group: root
    mode: 0666
  notify:
    - restart apache2
